version: '1.0.{build}'
image: Visual Studio 2017
clone_depth: 1

environment:
    RBushSnk:
        secure: bRWsKWiyC5IsQ3qxgMhQXxXHcGLZjXQLnNGGhcF3omgW1+pkiSCukD8ou9FpJdqBy9vO2SY9092MCXyiHWzZOdwfMUwnya5pRp4wVDdg3Y3u96WqT7ai/7dmQLYma/9hIshOiPX326a/T5ee1rbRIayBqZbfhTMPoHt6bnzlA3Y8lF6RVzEB5zJKnMZoCDpK98Mb5Y+mzXCiW5N/OhM5DaBrOtM56kthai2uh2IagWPIy9xpJ2f3ENk4lA4q7urZKTjz7lOvg/uc0ODMu9MHa8kVVed3nz/fn4pzYsRW88gmzKyOClQukXkBH4HldnQMWnef9lz19FFLFk1GEm5xG9HMGS3LMFpom5iQjO74biPbntxk+J6tpQLS88MsthL/RYSq6j2Qn3azMMEDCHzIMs8qBbCAn9+vgmLGuuhjxr56cuZ5tVTXHGnxxLvzTyphMgghYvckWZEuDwXUeJxgOkP79PeLUODNABWCy2ewPb9OxgsaI6G9tIfkbSkmgSPmDG4d3FJAdMuWBIA3sQYs8oPhVNgncEdCTWBs536Mn2xUvoKGd2M3C/y6AiamXXodc6vIUXzbPwgXA2C/XL55a/8XUNHJVeQU85vyReIKsVT4Rdh8lDxjwhfwugbKqpJKhQYVKZQlk56W1eEMET3hLFhpgGgjworMPit98SbxgdDW9W1uwuw7SEVdHrrd0HlWtPYxoymJ/YUcPEHDc5Vn1/iw0sxzmt0/Uf0QvbrK4SXJ5aN8clMY/Cwqok4DosV+sc+UzivomKBFgKFYgYo1DnugvyoOaSBknNwg+064KL5Ou00XLuV+HiThC/X4OIBNvYSkurGD+QvwkOek5yQwHEisDygkwxddqM2BowT2dBNoV7pkriwRjMWd5mQETSRJiWBh/0OLDvfEU+kPxreag0T0KlQ3sVwuYQNQIlzR9U9tdi7bng3PFBfyNR6/QOQiZBA4V0yDZzdm047/9w76DlsWNxWrTZlqnGzgNbftI0TcYMZBT9fDuxtWgJuFiFX1nm8sU2FfZUUrDA+7fAh0ne2nTLCxO3O6JijTXUlhJYI=

assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
  
before_build:
    - ps: >-
        Import-Module .\Module.psm1

        CreateAssemblyKeyFile "RBushSnk" "RBush.snk"

    - cmd: dotnet --version
    - cmd: dotnet restore --verbosity m

build_script:
    - cmd: dotnet publish ./RBush.KNN/RBush.KNN.csproj -c Release

test_script:
    - cmd: dotnet test

after_test:
    - cmd: nuget pack ./RBush.KNN/RBush.KNN.nuspec -version %appveyor_build_version%

artifacts:
  - path: RBush.KNN\bin\Release\netstandard1.2\RBush.dll
    name: RBush.KNN.dll
  - path: '**\*.nupkg'

cache:
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

deploy:
    provider: NuGet
    api_key:
        secure: PXXLxEGnQq6BGX+BDU+ll6IJplwZ3MdiSyGM2VTtP67ru2QvCyBXACs68quskxGo
    skip_symbols: true
    artifact: /.*\.nupkg/
    on: 
        branch: master
